services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - mynetwork

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - mynetwork
networks:
mynetwork: